import { IAppState } from './interfaces';

export const appState: IAppState = {
    email: '',
    password: '',
    rememberMe: false,
    fetching: false,
    token: '',
    redirect: false,
    dialog: false,
    isAuth: false,
    currentPage: 0,
};
// items: [
//     {
//         id: 'eryrey',
//         addr: ['ereryreyryerr'],
//         branch_ids: [1],
//         dob: '2020-10-06',
//         e_date: '2020-09-06',
//         email: ['erere@mh.ru'],
//         is_study: 0,
//         legal_type: 1,
//         name: 'evgeny',
//         phone: ['+7 (908) 665-97-22'],
//         balance: '0.0',
//         b_date: '2020-09-03',
//     },
//     {
//         id: 'upiouip',
//         addr: ['iopopiioopipi'],
//         balance: '0.0',
//         branch_ids: [1],
//         dob: '2020-09-29',
//         e_date: '2030-09-29',
//         email: ['eryuioop@tyii.ru'],
//         is_study: 0,
//         legal_type: 1,
//         name: 'wewewr',
//         phone: ['+7 (908) 665-97-22'],
//         b_date: '2020-10-05',
//     },
//     {
//         addr: ['From Magic'],
//         balance: '100.0',
//         branch_ids: [1],
//         dob: '2020-07-07',
//         e_date: '2030-07-07',
//         email: ['marun@gmail.com'],
//         id: 'upoipo',
//         is_study: 0,
//         legal_type: 1,
//         name: 'Maru',
//         phone: ['+7 (909) 123-45-67'],
//         b_date: '2020-07-09',
//     },
//     {
//         addr: ['From here'],
//         balance: '0.0',
//         branch_ids: [1],
//         dob: '2020-09-28',
//         e_date: '2030-07-07',
//         email: ['ml@gm.com'],
//         id: 'hjhj065',
//         is_study: 0,
//         legal_type: 1,
//         name: 'Mil',
//         phone: ['+7 (900) 111-22-33'],
//         b_date: '2020-10-05',
//     },
//     {
//         addr: ['LA'],
//         balance: '0.0',
//         branch_ids: [1],
//         dob: '2020-10-05',
//         e_date: '2030-10-05',
//         email: ['wetewt@ytyty.cg'],
//         id: 'dfgf2454364',
//         is_study: 0,
//         legal_type: 1,
//         name: 'Vlad',
//         phone: ['+7 (000) 111-22-33'],
//         b_date: '2020-10-05',
//     },
// ],
