import { IData } from './interfaces';

export const Dummy: IData = {
    total: 7,
    count: 7,
    page: 0,
    items: [
        {
            id: 2819,
            branch_ids: [5],
            teacher_ids: [],
            name: 'Аляева  Анастасия НИЧЕГО НЕТ',
            barcode: '',
            color: null,
            is_study: 1,
            study_status_id: null,
            lead_status_id: null,
            lead_reject_id: null,
            lead_source_id: null,
            assigned_id: null,
            legal_type: 1,
            legal_name: 'Аляева  Анастасия НИЧЕГО НЕТ',
            company_id: null,
            dob: '',
            balance: '1000.00',
            balance_base: '0.00',
            paid_count: 1,
            next_lesson_date: null,
            paid_till: null,
            last_attend_date: null,
            b_date: '2020-09-08 15:54:47',
            e_date: '2030-12-31',
            note: 'children+1598812501329 (3).csv',
            paid_lesson_count: 1,
            paid_lesson_date: null,
            phone: [],
            email: [],
            web: [],
            addr: [],
            custom_foto: null,
            custom_nomerkvitantsii: null,
            custom_pervyykontakt: null,
            custom_klassshkoly: '',
            custom_predmeta: '',
            custom_vyborpredmeta: '',
            custom_lokatsiyafilial: '',
        },
        {
            id: 1980,
            branch_ids: [5],
            teacher_ids: [],
            name: 'Клочихин Егор ( папа Денис Александрович)',
            barcode: '',
            color: null,
            is_study: 1,
            study_status_id: null,
            lead_status_id: null,
            lead_reject_id: null,
            lead_source_id: 19,
            assigned_id: null,
            legal_type: 1,
            legal_name: 'Клочихин Егор ( папа Денис Александрович)',
            company_id: null,
            dob: '',
            balance: '0.00',
            balance_base: '0.00',
            paid_count: 0,
            next_lesson_date: null,
            paid_till: null,
            last_attend_date: null,
            b_date: '2020-01-31 15:11:08',
            e_date: '2030-12-31',
            note: 'Без имени 1.csv',
            paid_lesson_count: 0,
            paid_lesson_date: null,
            phone: [],
            email: [],
            web: [],
            addr: [],
            custom_foto: null,
            custom_nomerkvitantsii: null,
            custom_pervyykontakt: null,
            custom_klassshkoly: null,
            custom_predmeta: null,
            custom_vyborpredmeta: null,
            custom_lokatsiyafilial: null,
        },
        {
            id: 1978,
            branch_ids: [5],
            teacher_ids: [],
            name: 'Пономарев Артем',
            barcode: '',
            color: null,
            is_study: 1,
            study_status_id: null,
            lead_status_id: null,
            lead_reject_id: null,
            lead_source_id: 18,
            assigned_id: null,
            legal_type: 1,
            legal_name: 'Пономарев Артем',
            company_id: null,
            dob: '',
            balance: '0.00',
            balance_base: '0.00',
            paid_count: 0,
            next_lesson_date: null,
            paid_till: null,
            last_attend_date: null,
            b_date: '2020-01-31 15:11:08',
            e_date: '2030-12-31',
            note: 'Без имени 1.csv',
            paid_lesson_count: 0,
            paid_lesson_date: null,
            phone: ['+7(960)799-51-05', '+7(960)795-84-97'],
            email: ['dddfdfd@erewrtewt.ru'],
            web: [],
            addr: [],
            custom_foto: '',
            custom_nomerkvitantsii: '',
            custom_pervyykontakt: '',
            custom_klassshkoly: '',
            custom_predmeta: '',
            custom_vyborpredmeta: '',
            custom_lokatsiyafilial: '',
        },
        {
            id: 1982,
            branch_ids: [5],
            teacher_ids: [],
            name: 'Сайт - Печерская Екатерина',
            barcode: '',
            color: null,
            is_study: 1,
            study_status_id: null,
            lead_status_id: null,
            lead_reject_id: null,
            lead_source_id: 8,
            assigned_id: 2,
            legal_type: 1,
            legal_name: 'Сайт - Печерская Екатерина',
            company_id: null,
            dob: '',
            balance: '0.00',
            balance_base: '0.00',
            paid_count: 0,
            next_lesson_date: null,
            paid_till: null,
            last_attend_date: null,
            b_date: '2020-01-31 15:11:08',
            e_date: '2030-12-31',
            note: 'Без имени 1.csv',
            paid_lesson_count: 0,
            paid_lesson_date: null,
            phone: [],
            email: [],
            web: [],
            addr: [],
            custom_foto: null,
            custom_nomerkvitantsii: null,
            custom_pervyykontakt: null,
            custom_klassshkoly: null,
            custom_predmeta: null,
            custom_vyborpredmeta: null,
            custom_lokatsiyafilial: null,
        },
        {
            id: 1979,
            branch_ids: [5],
            teacher_ids: [],
            name: 'Сергей Шарков',
            barcode: '',
            color: null,
            is_study: 1,
            study_status_id: null,
            lead_status_id: null,
            lead_reject_id: null,
            lead_source_id: 8,
            assigned_id: null,
            legal_type: 1,
            legal_name: 'Сергей Шарков',
            company_id: null,
            dob: '',
            balance: '0.00',
            balance_base: '0.00',
            paid_count: 0,
            next_lesson_date: null,
            paid_till: null,
            last_attend_date: null,
            b_date: '2020-01-31 15:11:08',
            e_date: '2030-12-31',
            note: 'Без имени 1.csv',
            paid_lesson_count: 0,
            paid_lesson_date: null,
            phone: [],
            email: [],
            web: [],
            addr: [],
            custom_foto: null,
            custom_nomerkvitantsii: null,
            custom_pervyykontakt: null,
            custom_klassshkoly: null,
            custom_predmeta: null,
            custom_vyborpredmeta: null,
            custom_lokatsiyafilial: null,
        },
        {
            id: 1983,
            branch_ids: [5],
            teacher_ids: [],
            name: 'Скорнякова Мария Валерьевна',
            barcode: '',
            color: null,
            is_study: 1,
            study_status_id: null,
            lead_status_id: null,
            lead_reject_id: null,
            lead_source_id: 4,
            assigned_id: 2,
            legal_type: 1,
            legal_name: 'Скорнякова Мария Валерьевна',
            company_id: null,
            dob: '',
            balance: '0.00',
            balance_base: '0.00',
            paid_count: 0,
            next_lesson_date: null,
            paid_till: null,
            last_attend_date: null,
            b_date: '2020-01-31 15:11:08',
            e_date: '2030-12-31',
            note: 'Без имени 1.csv',
            paid_lesson_count: 0,
            paid_lesson_date: null,
            phone: [],
            email: [],
            web: [],
            addr: [],
            custom_foto: null,
            custom_nomerkvitantsii: null,
            custom_pervyykontakt: null,
            custom_klassshkoly: null,
            custom_predmeta: null,
            custom_vyborpredmeta: null,
            custom_lokatsiyafilial: null,
        },
        {
            id: 2038,
            branch_ids: [5],
            teacher_ids: [],
            name: 'тест',
            barcode: '',
            color: null,
            is_study: 1,
            study_status_id: 4,
            lead_status_id: null,
            lead_reject_id: null,
            lead_source_id: null,
            assigned_id: null,
            legal_type: 1,
            legal_name: 'тест',
            company_id: null,
            dob: '',
            balance: '0.00',
            balance_base: '0.00',
            paid_count: 0,
            next_lesson_date: null,
            paid_till: null,
            last_attend_date: null,
            b_date: '2020-04-02 11:36:11',
            e_date: '2030-12-31',
            note: '',
            paid_lesson_count: 0,
            paid_lesson_date: null,
            phone: ['+7(923)730-04-53'],
            email: [],
            web: [],
            addr: [],
            custom_foto: null,
            custom_nomerkvitantsii: null,
            custom_pervyykontakt: null,
            custom_klassshkoly: null,
            custom_predmeta: null,
            custom_vyborpredmeta: null,
            custom_lokatsiyafilial: null,
        },
    ],
};
